---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/v1/users/{user_id}/baskets":
    parameters:
    - name: Authorization
      in: header
      type: string
      description: Token received from login
      required: true
    - name: user_id
      in: path
      type: string
      description: Id of the user
      required: true
    get:
      summary: show basket
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
    patch:
      summary: update basket
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            product_id:
              type: integer
            amount:
              type: integer
          required:
          - email
          - password
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
    delete:
      summary: delete basket
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
  "/v1/users/{user_id}/orders":
    parameters:
    - name: Authorization
      in: header
      type: string
      description: Token received from login
      required: true
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    get:
      summary: list orders
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
    post:
      summary: create order
      responses:
        '200':
          description: successful
        '400':
          description: No products in users basket
        '401':
          description: Unauthorized
        '500':
          description: Server error
  "/v1/users/{user_id}/orders/{id}":
    parameters:
    - name: user_id
      in: path
      type: string
      description: user_id
      required: true
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show order
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
  "/v1/products":
    parameters:
    - name: Authorization
      in: header
      type: string
      description: Token received from login
      required: true
    get:
      summary: list products
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
  "/v1/sessions":
    parameters:
    - name: body
      in: body
      required: true
      schema:
        type: object
        properties:
          email:
            type: string
          password:
            type: string
        required:
        - email
        - password
    post:
      summary: create session
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
  "/v1/users":
    parameters:
    - name: body
      in: body
      required: true
      schema:
        type: object
        properties:
          full_name:
            type: string
          email:
            type: string
          password:
            type: string
        required:
        - email
        - password
    post:
      summary: create user
      responses:
        '200':
          description: successful
        '400':
          description: Invalid user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
