source "https://rubygems.org"

ruby "3.2.2"
gem "rails", "~> 7.1.1"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'bcrypt'
gem 'jwt'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", '~> 6.0.0'
  gem "byebug"
end

group :test do
  gem 'database_cleaner'
end

group :development do
end

