source "https://rubygems.org"

ruby "3.2.2"
gem "rails", "~> 7.1.1"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'bcrypt'
gem 'jwt'
gem 'rswag'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "factory_girl_rails"
  gem 'rspec-rails'
  gem "byebug"
end

group :test do
  gem 'database_cleaner'
end

group :development do
end

